### PR TITLE
Add notebook to calc aca_offsets independently and check

### PR DESCRIPTION
**Pull request by jeanconn**
Add testing notebook to calc aca_offsets independently and check against dynamic aimpoint file.

### CODE REVIEW

**Comment by taldcroft** [comment]
Can you do this using the flight OR list in /data/mpcrit1 instead of copying the file into the repo?

**Comment by taldcroft** [comment]
I'm playing around with this now and may make a few edits.

**Comment by jeanconn** [comment]
Is there actually one around that has the ZERO offset aimpoint table?  I
just couldn't figure out where they were putting anything.

**Comment by jeanconn** [comment]
Cool.
And it looks like there is an OR  with the table in the sausage directory,
so I can use that.

fido: find -name "*.or" -exec grep -H ZERO {} \;
./JUL0415/oflso/sausage/JUL0415_A_orig.or:***ZERO-OFFSET AIMPOINTS START
./JUL0415/oflso/sausage/JUL0415_A_orig.or:***ZERO-OFFSET AIMPOINTS END
./MAR0516/oflso/sausage/MAR0516_A_orig.or:***ZERO-OFFSET AIMPOINTS START
./MAR0516/oflso/sausage/MAR0516_A_orig.or:***ZERO-OFFSET AIMPOINTS END

**Comment by jeanconn** [comment]
I can't use the "flight" list because it doesn't seem to have the table.​

**Comment by jeanconn** [comment]
This could probably still use text edits, but it has had some review at this point so I'm pushing to master to make it easier to find.

**Pull request merged**
